#! /bin/bash

rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
rosrun all_listeners robot_AI_training.py 
